apiVersion: v1
kind: ConfigMap
metadata:
  name: scb-ast-otp-service-configmap
  namespace: ast-dev
data:
  application.yaml: |+
    server:
      port: 8080
    
    app:
      limit: 5
      wrongLimit: 3
      plusMinutes: 3
    
    redis:
      server: localhost
      port: 6379

