apiVersion: v1
kind: Service
metadata:
  name: scb-ast-otp-service-service
  namespace: ast-dev
  labels:
    app: scb-ast-otp-service-label
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: scb-ast-otp-service-deployment

